import type { ExploreModel } from '@shared/types/explore'

/**
 * Curated catalog of popular open-source models available on HuggingFace.
 * These are real models that can run locally in GGUF/MLX format.
 */
export const MODEL_CATALOG: ExploreModel[] = [
  {
    id: 'qwen3.8-27b',
    name: 'Qwen3.8 27B',
    slug: 'Qwen/Qwen3-27B',
    author: 'Qwen',
    description: 'State-of-the-art laptop size model capable of reasoning, tool calling, and image understanding.',
    longDescription: 'Qwen3.8 27B is a compact, deployment-friendly dense vision-language model built on the Qwen3.5 architecture. It delivers stronger performance across coding, professional work, research, and long-horizon agentic tasks.',
    downloads: 872724,
    likes: 93,
    staffPick: true,
    updatedAt: '2026-08-18',
    parameters: '27B',
    architecture: 'qwen3',
    capabilities: ['Vision', 'Tools', 'Reasoning'],
    files: [
      { format: 'GGUF', quantization: 'Q4_K_M', sizeGB: 17.74, downloadUrl: '' },
      { format: 'GGUF', quantization: 'Q5_K_S', sizeGB: 20.87, downloadUrl: '' },
      { format: 'GGUF', quantization: 'Q8_0', sizeGB: 28.68, downloadUrl: '' },
      { format: 'MLX', sizeGB: 22.0, downloadUrl: '' },
    ],
    tags: ['text-generation', 'code', 'reasoning', 'vision'],
    iconType: 'qwen',
  },
  {
    id: 'qwen3.6-27b',
    name: 'Qwen3.6 27B',
    slug: 'Qwen/Qwen3.6-27B',
    author: 'Qwen',
    description: 'Dense 27B Qwen 3.6 prioritizes stability and real-world reliability.',
    longDescription: 'Dense 27B Qwen 3.6 prioritizes stability and real-world reliability over raw benchmark chasing. A solid all-rounder for local deployment.',
    downloads: 412000,
    likes: 67,
    staffPick: false,
    updatedAt: '2026-05-03',
    parameters: '27B',
    architecture: 'qwen3',
    capabilities: ['Tools', 'Reasoning'],
    files: [
      { format: 'GGUF', quantization: 'Q4_K_M', sizeGB: 17.74, downloadUrl: '' },
      { format: 'GGUF', quantization: 'Q5_K_S', sizeGB: 20.87, downloadUrl: '' },
      { format: 'MLX', sizeGB: 22.0, downloadUrl: '' },
    ],
    tags: ['text-generation', 'code', 'reasoning'],
    iconType: 'qwen',
  },
  {
    id: 'gemma4-12b-qat',
    name: 'Gemma 4 12B QAT',
    slug: 'google/gemma-4-12b-qat',
    author: 'Google',
    description: 'Gemma 4 12B optimized with Quantization-Aware Training for better quality at smaller sizes.',
    longDescription: 'Gemma 4 12B optimized with Quantization-Aware Training (QAT). Delivers near-full-precision quality in quantized formats, ideal for local deployment.',
    downloads: 305000,
    likes: 54,
    staffPick: true,
    updatedAt: '2026-08-05',
    parameters: '12B',
    architecture: 'gemma',
    capabilities: ['Vision', 'Tools', 'Reasoning'],
    files: [
      { format: 'GGUF', quantization: 'Q4_K_M', sizeGB: 8.12, downloadUrl: '' },
      { format: 'GGUF', quantization: 'Q5_K_S', sizeGB: 9.52, downloadUrl: '' },
      { format: 'MLX', sizeGB: 9.6, downloadUrl: '' },
    ],
    tags: ['text-generation', 'code', 'vision', 'reasoning'],
    iconType: 'google',
  },
  {
    id: 'gemma4-26b-a4b-qat',
    name: 'Gemma 4 26B A4B QAT',
    slug: 'google/gemma-4-26b-a4b-qat',
    author: 'Google',
    description: 'Gemma 4 26B A4B optimized with Quantization-Aware Training.',
    longDescription: 'Gemma 4 26B with only 4B active parameters (MoE). Optimized with QAT for excellent quality with low inference cost.',
    downloads: 283000,
    likes: 48,
    staffPick: true,
    updatedAt: '2026-08-05',
    parameters: '26B (4B active)',
    architecture: 'gemma',
    capabilities: ['Vision', 'Tools', 'Reasoning'],
    files: [
      { format: 'GGUF', quantization: 'Q4_K_M', sizeGB: 12.5, downloadUrl: '' },
      { format: 'GGUF', quantization: 'Q5_K_S', sizeGB: 14.2, downloadUrl: '' },
      { format: 'MLX', sizeGB: 13.8, downloadUrl: '' },
    ],
    tags: ['text-generation', 'code', 'vision', 'mixture-of-experts'],
    iconType: 'google',
  },
  {
    id: 'gemma4-31b-qat',
    name: 'Gemma 4 31B QAT',
    slug: 'google/gemma-4-31b-qat',
    author: 'Google',
    description: 'Gemma 4 31B optimized with Quantization-Aware Training.',
    longDescription: 'Gemma 4 31B is the flagship dense model from Google, optimized with QAT for local deployment.',
    downloads: 198000,
    likes: 42,
    staffPick: true,
    updatedAt: '2026-08-05',
    parameters: '31B',
    architecture: 'gemma',
    capabilities: ['Vision', 'Tools', 'Reasoning'],
    files: [
      { format: 'GGUF', quantization: 'Q4_K_M', sizeGB: 19.8, downloadUrl: '' },
      { format: 'GGUF', quantization: 'Q5_K_S', sizeGB: 23.1, downloadUrl: '' },
      { format: 'MLX', sizeGB: 24.0, downloadUrl: '' },
    ],
    tags: ['text-generation', 'code', 'vision', 'reasoning'],
    iconType: 'google',
  },
  {
    id: 'gemma4-12b',
    name: 'Gemma 4 12B',
    slug: 'google/gemma-4-12b',
    author: 'Google',
    description: 'The new Gemma 4 12B Unified reasoning model.',
    longDescription: 'Gemma 4 12B is a unified reasoning model from Google, supporting both text and vision tasks with strong performance.',
    downloads: 267000,
    likes: 39,
    staffPick: false,
    updatedAt: '2026-08-05',
    parameters: '12B',
    architecture: 'gemma',
    capabilities: ['Vision', 'Reasoning'],
    files: [
      { format: 'GGUF', quantization: 'Q4_K_M', sizeGB: 7.42, downloadUrl: '' },
      { format: 'GGUF', quantization: 'Q5_K_S', sizeGB: 8.65, downloadUrl: '' },
      { format: 'MLX', sizeGB: 8.8, downloadUrl: '' },
    ],
    tags: ['text-generation', 'vision', 'reasoning'],
    iconType: 'google',
  },
  {
    id: 'bonsai-27b',
    name: 'Bonsai 27B',
    slug: 'microsoft/Bonsai-27B',
    author: 'Microsoft',
    description: 'Bonsai is a 27B model, but takes only about 4GB with quantization.',
    longDescription: 'Bonsai 27B is a highly compressed model from Microsoft that delivers strong performance while fitting in surprisingly little memory.',
    downloads: 189000,
    likes: 71,
    staffPick: true,
    updatedAt: '2026-08-01',
    parameters: '27B',
    architecture: 'qwen3',
    capabilities: ['Code', 'Reasoning'],
    files: [
      { format: 'GGUF', quantization: 'Q4_K_M', sizeGB: 4.0, downloadUrl: '' },
      { format: 'GGUF', quantization: 'Q5_K_S', sizeGB: 4.8, downloadUrl: '' },
      { format: 'GGUF', quantization: 'Q8_0', sizeGB: 6.5, downloadUrl: '' },
    ],
    tags: ['text-generation', 'code', 'reasoning', 'compressed'],
    iconType: 'microsoft',
  },
  {
    id: 'gemma4-31b',
    name: 'Gemma 4 31B',
    slug: 'google/gemma-4-31b',
    author: 'Google',
    description: '31B dense Gemma4 variant. Supports vision input.',
    longDescription: 'Gemma 4 31B is the full dense 31B parameter model from Google with vision support and strong reasoning capabilities.',
    downloads: 156000,
    likes: 35,
    staffPick: false,
    updatedAt: '2026-08-05',
    parameters: '31B',
    architecture: 'gemma',
    capabilities: ['Vision', 'Tools', 'Reasoning'],
    files: [
      { format: 'GGUF', quantization: 'Q4_K_M', sizeGB: 19.8, downloadUrl: '' },
      { format: 'GGUF', quantization: 'Q5_K_S', sizeGB: 23.1, downloadUrl: '' },
      { format: 'MLX', sizeGB: 24.0, downloadUrl: '' },
    ],
    tags: ['text-generation', 'vision', 'reasoning'],
    iconType: 'google',
  },
  {
    id: 'gemma4-e4b',
    name: 'Gemma 4 E4B',
    slug: 'google/gemma-4-e4b',
    author: 'Google',
    description: 'Gemma4, effective 4B version. Supports image input.',
    longDescription: 'Gemma 4 E4B is an efficient 4B parameter model that supports image input, ideal for resource-constrained devices.',
    downloads: 445000,
    likes: 62,
    staffPick: false,
    updatedAt: '2026-08-05',
    parameters: '4B',
    architecture: 'gemma',
    capabilities: ['Vision'],
    files: [
      { format: 'GGUF', quantization: 'Q4_K_M', sizeGB: 2.87, downloadUrl: '' },
      { format: 'GGUF', quantization: 'Q5_K_S', sizeGB: 3.34, downloadUrl: '' },
      { format: 'MLX', sizeGB: 3.2, downloadUrl: '' },
    ],
    tags: ['text-generation', 'vision', 'efficient'],
    iconType: 'google',
  },
  {
    id: 'gemma4-e2b',
    name: 'Gemma 4 E2B',
    slug: 'google/gemma-4-e2b',
    author: 'Google',
    description: 'Gemma4, effective 2B version. Supports image input.',
    longDescription: 'Gemma 4 E2B is the smallest Gemma 4 model, perfect for edge devices and mobile while still supporting image input.',
    downloads: 520000,
    likes: 58,
    staffPick: false,
    updatedAt: '2026-08-05',
    parameters: '2B',
    architecture: 'gemma',
    capabilities: ['Vision'],
    files: [
      { format: 'GGUF', quantization: 'Q4_K_M', sizeGB: 1.67, downloadUrl: '' },
      { format: 'GGUF', quantization: 'Q8_0', sizeGB: 2.15, downloadUrl: '' },
      { format: 'MLX', sizeGB: 1.8, downloadUrl: '' },
    ],
    tags: ['text-generation', 'vision', 'edge', 'efficient'],
    iconType: 'google',
  },
  {
    id: 'llama-3.3-70b',
    name: 'Llama 3.3 70B',
    slug: 'meta-llama/Llama-3.3-70B-Instruct',
    author: 'Meta',
    description: 'Meta\'s flagship 70B open model with strong general performance.',
    longDescription: 'Llama 3.3 70B is Meta\'s most capable open model, delivering near-GPT-4 level performance on a wide range of tasks.',
    downloads: 1200000,
    likes: 312,
    staffPick: true,
    updatedAt: '2026-07-15',
    parameters: '70B',
    architecture: 'llama',
    capabilities: ['Code', 'Reasoning', 'Tools'],
    files: [
      { format: 'GGUF', quantization: 'Q4_K_M', sizeGB: 40.5, downloadUrl: '' },
      { format: 'GGUF', quantization: 'Q5_K_S', sizeGB: 47.8, downloadUrl: '' },
    ],
    tags: ['text-generation', 'code', 'reasoning', 'general'],
    iconType: 'meta',
  },
  {
    id: 'llama-3.2-3b',
    name: 'Llama 3.2 3B',
    slug: 'meta-llama/Llama-3.2-3B-Instruct',
    author: 'Meta',
    description: 'Fast, lightweight Llama model perfect for edge deployment.',
    longDescription: 'Llama 3.2 3B is optimized for speed and efficiency, making it ideal for edge devices and real-time applications.',
    downloads: 890000,
    likes: 178,
    staffPick: false,
    updatedAt: '2026-06-20',
    parameters: '3B',
    architecture: 'llama',
    capabilities: ['Code'],
    files: [
      { format: 'GGUF', quantization: 'Q4_K_M', sizeGB: 2.05, downloadUrl: '' },
      { format: 'GGUF', quantization: 'Q8_0', sizeGB: 3.27, downloadUrl: '' },
      { format: 'MLX', sizeGB: 2.2, downloadUrl: '' },
    ],
    tags: ['text-generation', 'code', 'edge', 'efficient'],
    iconType: 'meta',
  },
  {
    id: 'mistral-small-24b',
    name: 'Mistral Small 24B',
    slug: 'mistralai/Mistral-Small-24B-Instruct-2501',
    author: 'Mistral AI',
    description: 'Mistral\'s efficient 24B model with strong coding abilities.',
    longDescription: 'Mistral Small 24B offers an excellent balance of performance and efficiency, with particularly strong coding capabilities.',
    downloads: 567000,
    likes: 145,
    staffPick: true,
    updatedAt: '2026-07-28',
    parameters: '24B',
    architecture: 'mistral',
    capabilities: ['Code', 'Reasoning', 'Tools'],
    files: [
      { format: 'GGUF', quantization: 'Q4_K_M', sizeGB: 14.3, downloadUrl: '' },
      { format: 'GGUF', quantization: 'Q5_K_S', sizeGB: 16.8, downloadUrl: '' },
      { format: 'MLX', sizeGB: 15.5, downloadUrl: '' },
    ],
    tags: ['text-generation', 'code', 'reasoning'],
    iconType: 'mistral',
  },
  {
    id: 'deepseek-r1-0528',
    name: 'DeepSeek R1 0528',
    slug: 'deepseek-ai/DeepSeek-R1-0528',
    author: 'DeepSeek',
    description: 'DeepSeek\'s reasoning model with advanced chain-of-thought.',
    longDescription: 'DeepSeek R1 0528 is a specialized reasoning model that uses advanced chain-of-thought to solve complex problems.',
    downloads: 780000,
    likes: 201,
    staffPick: true,
    updatedAt: '2026-05-28',
    parameters: '671B (37B active)',
    architecture: 'deepseek',
    capabilities: ['Reasoning', 'Code', 'Tools'],
    files: [
      { format: 'GGUF', quantization: 'Q4_K_M', sizeGB: 48.0, downloadUrl: '' },
      { format: 'GGUF', quantization: 'Q5_K_S', sizeGB: 55.0, downloadUrl: '' },
    ],
    tags: ['text-generation', 'reasoning', 'code', 'chain-of-thought'],
    iconType: 'deepseek',
  },
  {
    id: 'deepseek-v3-0324',
    name: 'DeepSeek V3 0324',
    slug: 'deepseek-ai/DeepSeek-V3-0324',
    author: 'DeepSeek',
    description: 'DeepSeek V3 — strong general-purpose MoE model.',
    longDescription: 'DeepSeek V3 0324 is a powerful mixture-of-experts model with strong general performance across coding, math, and language tasks.',
    downloads: 650000,
    likes: 176,
    staffPick: false,
    updatedAt: '2026-03-24',
    parameters: '671B (37B active)',
    architecture: 'deepseek',
    capabilities: ['Code', 'Reasoning', 'Tools'],
    files: [
      { format: 'GGUF', quantization: 'Q4_K_M', sizeGB: 48.0, downloadUrl: '' },
    ],
    tags: ['text-generation', 'code', 'reasoning', 'mixture-of-experts'],
    iconType: 'deepseek',
  },
  {
    id: 'phi-4-reasoning-plus',
    name: 'Phi-4 Reasoning Plus',
    slug: 'microsoft/Phi-4-reasoning-plus',
    author: 'Microsoft',
    description: 'Microsoft\'s reasoning-focused model with enhanced math and code.',
    longDescription: 'Phi-4 Reasoning Plus is a compact but powerful reasoning model from Microsoft, excelling at math, code, and logical reasoning.',
    downloads: 420000,
    likes: 98,
    staffPick: true,
    updatedAt: '2026-07-10',
    parameters: '14B',
    architecture: 'phi',
    capabilities: ['Code', 'Reasoning'],
    files: [
      { format: 'GGUF', quantization: 'Q4_K_M', sizeGB: 8.63, downloadUrl: '' },
      { format: 'GGUF', quantization: 'Q5_K_S', sizeGB: 10.1, downloadUrl: '' },
      { format: 'MLX', sizeGB: 9.2, downloadUrl: '' },
    ],
    tags: ['text-generation', 'code', 'reasoning', 'math'],
    iconType: 'microsoft',
  },
  {
    id: 'qwen3.5-14b',
    name: 'Qwen3.5 14B',
    slug: 'Qwen/Qwen3.5-14B',
    author: 'Qwen',
    description: 'Compact 14B model with strong multilingual and coding support.',
    longDescription: 'Qwen3.5 14B is a well-balanced model offering strong multilingual capabilities and excellent coding performance.',
    downloads: 380000,
    likes: 82,
    staffPick: false,
    updatedAt: '2026-07-22',
    parameters: '14B',
    architecture: 'qwen3',
    capabilities: ['Code', 'Reasoning', 'Tools'],
    files: [
      { format: 'GGUF', quantization: 'Q4_K_M', sizeGB: 8.78, downloadUrl: '' },
      { format: 'GGUF', quantization: 'Q5_K_S', sizeGB: 10.3, downloadUrl: '' },
      { format: 'MLX', sizeGB: 9.5, downloadUrl: '' },
    ],
    tags: ['text-generation', 'code', 'multilingual'],
    iconType: 'qwen',
  },
  {
    id: 'gemma-3-27b-it',
    name: 'Gemma 3 27B IT',
    slug: 'google/gemma-3-27b-it',
    author: 'Google',
    description: 'Previous-gen Gemma 27B instruction-tuned model.',
    longDescription: 'Gemma 3 27B IT is Google\'s previous generation instruction-tuned 27B model. Still highly capable for many tasks.',
    downloads: 620000,
    likes: 134,
    staffPick: false,
    updatedAt: '2026-04-10',
    parameters: '27B',
    architecture: 'gemma',
    capabilities: ['Code', 'Reasoning'],
    files: [
      { format: 'GGUF', quantization: 'Q4_K_M', sizeGB: 16.1, downloadUrl: '' },
      { format: 'GGUF', quantization: 'Q5_K_S', sizeGB: 18.8, downloadUrl: '' },
      { format: 'MLX', sizeGB: 17.5, downloadUrl: '' },
    ],
    tags: ['text-generation', 'code', 'instruction-tuned'],
    iconType: 'google',
  },
  {
    id: 'llama-3.1-8b',
    name: 'Llama 3.1 8B',
    slug: 'meta-llama/Llama-3.1-8B-Instruct',
    author: 'Meta',
    description: 'Versatile 8B model with strong all-around performance.',
    longDescription: 'Llama 3.1 8B is a versatile model that punches above its weight class, suitable for a wide range of tasks.',
    downloads: 1500000,
    likes: 289,
    staffPick: false,
    updatedAt: '2026-03-15',
    parameters: '8B',
    architecture: 'llama',
    capabilities: ['Code', 'Reasoning'],
    files: [
      { format: 'GGUF', quantization: 'Q4_K_M', sizeGB: 4.92, downloadUrl: '' },
      { format: 'GGUF', quantization: 'Q8_0', sizeGB: 8.54, downloadUrl: '' },
      { format: 'MLX', sizeGB: 5.5, downloadUrl: '' },
    ],
    tags: ['text-generation', 'code', 'general'],
    iconType: 'meta',
  },
  {
    id: 'mistral-nemo-12b',
    name: 'Mistral Nemo 12B',
    slug: 'mistralai/Mistral-Nemo-Instruct-2407',
    author: 'Mistral AI',
    description: 'Compact 12B model with 128k context window.',
    longDescription: 'Mistral Nemo 12B is a compact model with an exceptionally long 128k context window, ideal for document analysis.',
    downloads: 480000,
    likes: 112,
    staffPick: false,
    updatedAt: '2026-07-01',
    parameters: '12B',
    architecture: 'mistral',
    capabilities: ['Code', 'Reasoning'],
    files: [
      { format: 'GGUF', quantization: 'Q4_K_M', sizeGB: 7.13, downloadUrl: '' },
      { format: 'GGUF', quantization: 'Q5_K_S', sizeGB: 8.39, downloadUrl: '' },
      { format: 'MLX', sizeGB: 7.8, downloadUrl: '' },
    ],
    tags: ['text-generation', 'code', 'long-context'],
    iconType: 'mistral',
  },
  {
    id: 'qwen2.5-coder-32b',
    name: 'Qwen2.5 Coder 32B',
    slug: 'Qwen/Qwen2.5-Coder-32B-Instruct',
    author: 'Qwen',
    description: 'Specialized coding model with 32B parameters.',
    longDescription: 'Qwen2.5 Coder 32B is a specialized coding model that excels at code generation, completion, and understanding across 90+ languages.',
    downloads: 920000,
    likes: 234,
    staffPick: true,
    updatedAt: '2026-06-15',
    parameters: '32B',
    architecture: 'qwen3',
    capabilities: ['Code', 'Reasoning'],
    files: [
      { format: 'GGUF', quantization: 'Q4_K_M', sizeGB: 19.8, downloadUrl: '' },
      { format: 'GGUF', quantization: 'Q5_K_S', sizeGB: 23.2, downloadUrl: '' },
      { format: 'MLX', sizeGB: 21.0, downloadUrl: '' },
    ],
    tags: ['text-generation', 'code', 'programming'],
    iconType: 'qwen',
  },
]

export function sortModels(models: ExploreModel[], sortBy: string): ExploreModel[] {
  const sorted = [...models]
  switch (sortBy) {
    case 'likes':
      return sorted.sort((a, b) => b.likes - a.likes)
    case 'downloads':
      return sorted.sort((a, b) => b.downloads - a.downloads)
    case 'lastModified':
      return sorted.sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime())
    case 'recommended':
    default:
      return sorted.sort((a, b) => {
        if (a.staffPick !== b.staffPick) return a.staffPick ? -1 : 1
        return b.likes - a.likes
      })
  }
}

export function filterModels(models: ExploreModel[], query: string): ExploreModel[] {
  if (!query.trim()) return models
  const q = query.toLowerCase()
  return models.filter(
    (m) =>
      m.name.toLowerCase().includes(q) ||
      m.author.toLowerCase().includes(q) ||
      m.description.toLowerCase().includes(q) ||
      m.tags.some((t) => t.includes(q))
  )
}
