/**
 * Single source of IPC channels — imported by main, preload, renderer (types only).
 * Enforced by preload whitelist; handlers validate with zod.
 */
export const IPC_CHANNELS = {
  'app:getInfo': { type: 'invoke' as const },
  'app:getSystem': { type: 'invoke' as const },
  'system:getResources': { type: 'invoke' as const },
  'sessions:list': { type: 'invoke' as const },
  'sessions:create': { type: 'invoke' as const },
  'sessions:getEvents': { type: 'invoke' as const },
  'sessions:rename': { type: 'invoke' as const },
  'sessions:delete': { type: 'invoke' as const },
  'projects:list': { type: 'invoke' as const },
  'projects:create': { type: 'invoke' as const },
  'projects:rename': { type: 'invoke' as const },
  'projects:delete': { type: 'invoke' as const },
  'sessions:archive': { type: 'invoke' as const },
  'sessions:unarchive': { type: 'invoke' as const },
  'sessions:listArchived': { type: 'invoke' as const },
  'chat:send': { type: 'invoke' as const },
  'artifacts:open': { type: 'invoke' as const },
  'clipboard:write': { type: 'invoke' as const },
  'chat:cancel': { type: 'invoke' as const },
  'chat:approve': { type: 'invoke' as const },
  'chat:regenerate': { type: 'invoke' as const },
  'chat:editResend': { type: 'invoke' as const },
  'models:probeRuntime': { type: 'invoke' as const },
  /** One-time owned-runtime install (pinned llama.cpp CUDA build). */
  'models:ensureRuntime': { type: 'invoke' as const },
  'models:diagnoseRuntime': { type: 'invoke' as const },
  'models:unblockRuntime': { type: 'invoke' as const },
  // Commit 6 — workbench facet (registry/probe/select)
  'models:listRuntimes': { type: 'invoke' as const },
  'models:addRuntime': { type: 'invoke' as const },
  'models:removeRuntime': { type: 'invoke' as const },
  'models:testConnection': { type: 'invoke' as const },
  'models:listModels': { type: 'invoke' as const },
  'models:selectModel': { type: 'invoke' as const },
  'models:getActiveModel': { type: 'invoke' as const },
  // Settings (preferences)
  'settings:get': { type: 'invoke' as const },
  'settings:set': { type: 'invoke' as const },
  // App version + update feed (Settings → General)
  'app:getVersion': { type: 'invoke' as const },
  'updates:checkNow': { type: 'invoke' as const },
  'updates:download': { type: 'invoke' as const },
  'updates:install': { type: 'invoke' as const },
  'updates:event': { type: 'on' as const },
  // Usage stats
  'usage:getTotal': { type: 'invoke' as const },
  'usage:getByModel': { type: 'invoke' as const },
  'usage:getRecent': { type: 'invoke' as const },
  // Window controls (frameless window)
  'window:minimize': { type: 'invoke' as const },
  'window:maximize': { type: 'invoke' as const },
  'window:close': { type: 'invoke' as const },
  // Dialog
  'dialog:pickFolder': { type: 'invoke' as const },
  // Skills scanning
  'skills:scan': { type: 'invoke' as const },
  'skills:toggle': { type: 'invoke' as const },
  'skills:listBionic': { type: 'invoke' as const },
  'skills:addBionic': { type: 'invoke' as const },
  'skills:removeBionic': { type: 'invoke' as const },
  'skills:listDetailed': { type: 'invoke' as const },
  'skills:importFromUrl': { type: 'invoke' as const },
  // Explore (HuggingFace catalog)
  'explore:listModels': { type: 'invoke' as const },
  'explore:getModel': { type: 'invoke' as const },
  'explore:getCompatibility': { type: 'invoke' as const },
  'explore:getRecommendations': { type: 'invoke' as const },
  'explore:getHardwareProfile': { type: 'invoke' as const },
  'runtime:detectExternal': { type: 'invoke' as const },
  // Library (downloaded models)
  'library:listModels': { type: 'invoke' as const },
  'library:getDirectory': { type: 'invoke' as const },
  'library:detectLocations': { type: 'invoke' as const },
  'library:setDirectory': { type: 'invoke' as const },
  'library:registerExternal': { type: 'invoke' as const },
  'library:revealInFolder': { type: 'invoke' as const },
  'library:download': { type: 'invoke' as const },
  'library:cancelDownload': { type: 'invoke' as const },
  'library:pauseDownload': { type: 'invoke' as const },
  'library:resumeDownload': { type: 'invoke' as const },
  'library:getActiveDownloads': { type: 'invoke' as const },
  'library:isDownloaded': { type: 'invoke' as const },
  'library:getFileStatus': { type: 'invoke' as const },
  'library:reconcile': { type: 'invoke' as const },
  'library:openFolder': { type: 'invoke' as const },
  'library:delete': { type: 'invoke' as const },
  'shell:openExternal': { type: 'invoke' as const },
  'shell:showItemInFolder': { type: 'invoke' as const },
  // Git working-copy review (right-rail Files Changed) + wiki knowledge graph
  'git:status': { type: 'invoke' as const },
  'git:diff': { type: 'invoke' as const },
  'git:fileContent': { type: 'invoke' as const },
  'wiki:buildGraph': { type: 'invoke' as const },
  // Persistent shell terminals (right-rail Terminal, pipes-based)
  'terminal:create': { type: 'invoke' as const },
  'terminal:write': { type: 'invoke' as const },
  'terminal:resize': { type: 'invoke' as const },
  'terminal:kill': { type: 'invoke' as const },
  'terminal:list': { type: 'invoke' as const },
  'terminal:tail': { type: 'invoke' as const },
  'terminal:output': { type: 'on' as const },
  'terminal:exit': { type: 'on' as const },
  // Agent Studio (real backends for the Agents page)
  'agents:list': { type: 'invoke' as const },
  'agents:create': { type: 'invoke' as const },
  'agents:update': { type: 'invoke' as const },
  'agents:duplicate': { type: 'invoke' as const },
  'agents:remove': { type: 'invoke' as const },
  'agents:archive': { type: 'invoke' as const },
  'agents:knowledge:list': { type: 'invoke' as const },
  'agents:knowledge:add': { type: 'invoke' as const },
  'agents:knowledge:remove': { type: 'invoke' as const },
  'agents:memory:list': { type: 'invoke' as const },
  'agents:memory:add': { type: 'invoke' as const },
  'agents:memory:remove': { type: 'invoke' as const },
  'agents:workflows:list': { type: 'invoke' as const },
  'agents:workflows:create': { type: 'invoke' as const },
  'agents:workflows:update': { type: 'invoke' as const },
  'agents:workflows:remove': { type: 'invoke' as const },
  'agents:evals:list': { type: 'invoke' as const },
  'agents:evals:record': { type: 'invoke' as const },
  'agents:versions:list': { type: 'invoke' as const },
  'agents:versions:save': { type: 'invoke' as const },
  'agents:permissions:get': { type: 'invoke' as const },
  'agents:permissions:set': { type: 'invoke' as const },
  // Exec permissions (AI command levels)
  'exec:getMode': { type: 'invoke' as const },
  'exec:setMode': { type: 'invoke' as const },
  // Tools (gated by exec permission level)
  'tools:list': { type: 'invoke' as const },
  'tools:dispatch': { type: 'invoke' as const },
  // MCP servers (Connected Apps) — global MCP folder + URL AI install
  'mcp:list': { type: 'invoke' as const },
  'mcp:add': { type: 'invoke' as const },
  'mcp:installFromUrl': { type: 'invoke' as const },
  'mcp:getDir': { type: 'invoke' as const },
  'mcp:openFolder': { type: 'invoke' as const },
  'mcp:remove': { type: 'invoke' as const },
  'mcp:toggle': { type: 'invoke' as const },
  'mcp:probe': { type: 'invoke' as const },
  // Loaded instances (runtime monitoring & management)
  'instances:list': { type: 'invoke' as const },
  'instances:unload': { type: 'invoke' as const },
  'instances:getMetrics': { type: 'invoke' as const },
  'logs:getRecent': { type: 'invoke' as const },
  'events:session': { type: 'on' as const },
  'events:download': { type: 'on' as const },
  'events:instances': { type: 'on' as const },
} as const

export type IpcChannel = keyof typeof IPC_CHANNELS
export type IpcInvokeChannel = {
  [K in IpcChannel]: (typeof IPC_CHANNELS)[K]['type'] extends 'invoke' ? K : never
}[IpcChannel]
export type IpcOnChannel = {
  [K in IpcChannel]: (typeof IPC_CHANNELS)[K]['type'] extends 'on' ? K : never
}[IpcChannel]
