"""Move the protobuf repair into the install cell, before vllm's entry point.

v17 installed vLLM successfully - torch 2.13.0+cu130, vllm 0.30.0, all five
Gemma4 architectures registered - and then died on the very next line:

    VersionError: Detected mismatched Protobuf Gencode/Runtime major versions
    when loading google/protobuf/duration.proto: gencode 7.36.2 runtime 5.29.5

Read that carefully: the GENCODE is 7.36.2 and the RUNTIME is 5.29.5. A
descriptor file compiled into a package that arrived with the vLLM install was
generated by protobuf 7.36.2, but the installed protobuf library is still the
runner's 5.29.5. Protobuf requires a matching major version on both sides.

The subprocess probe passed only because a bare `import vllm` never loads those
descriptors; `from vllm import LLM, SamplingParams` does. So the repair has to
happen BEFORE the in-process entry-point import, inside the install cell. It
was in the fetch cell, which is one cell too late: the failure happened in the
install cell, before the fetch cell ever ran.
"""
import ast
import io
import pathlib

P = pathlib.Path(__file__).parent / "vllm_cells.py"
src = io.open(P, encoding="utf-8").read()

REPAIR = '''
# Step 2: repair protobuf BEFORE importing vllm's entry point in this process.
#
# v17 installed vLLM fine (torch 2.13.0+cu130, vllm 0.30.0, all five Gemma4
# architectures registered) and then died on this very import with:
#   VersionError: Detected mismatched Protobuf Gencode/Runtime major versions
#   when loading google/protobuf/duration.proto: gencode 7.36.2 runtime 5.29.5
#
# The gencode is 7.36.2, the runtime is 5.29.5: a descriptor compiled into a
# package that arrived with the vLLM install needs protobuf 7, but the runner's
# protobuf library is 5.29.5. Mismatched majors are rejected outright. The
# subprocess probe passed only because a bare `import vllm` never loads those
# descriptors; `from vllm import LLM` does.
def _protobuf_version():
    p = subprocess.run([sys.executable, "-c",
                        "import google.protobuf as g; print('PB ' + g.__version__)"],
                       capture_output=True, text=True, timeout=300)
    ln = next((l for l in (p.stdout or "").splitlines() if l.startswith("PB ")), "")
    return ln[3:].strip() if ln else None

_pb = _protobuf_version()
diag("protobuf_before", ok=bool(_pb), protobuf=_pb)
if _pb and int(_pb.split(".")[0]) < 7:
    rc_pb = run(f"{sys.executable} -m pip install -q --upgrade protobuf>=7,<8")
    _pb2 = _protobuf_version()
    diag("protobuf_upgrade",
         ok=(rc_pb == 0 and bool(_pb2) and int(_pb2.split(".")[0]) >= 7),
         returncode=rc_pb, before=_pb, after=_pb2)
    if rc_pb != 0 or not _pb2 or int(_pb2.split(".")[0]) < 7:
        run(f"{sys.executable} -m pip install -q protobuf>=5,<6")
        diag("protobuf_fallback", ok=True, after=_protobuf_version(),
             note="went back to the runner 5.x instead")

# Verify the REAL entry point in a subprocess first, so a failure arrives as a
# readable message rather than an exception from inside this cell.
_vcheck = subprocess.run(
    [sys.executable, "-c",
     "from vllm import LLM, SamplingParams;"
     "from vllm.lora.request import LoRARequest;"
     "from vllm.inputs import TokensPrompt;"
     "import vllm, google.protobuf as g;"
     "print('VC ' + vllm.__version__ + ' pb=' + g.__version__)"],
    capture_output=True, text=True, timeout=900)
_ln = next((l for l in (_vcheck.stdout or "").splitlines() if l.startswith("VC ")), "")
diag("vllm_entrypoint_import", ok=(_vcheck.returncode == 0 and bool(_ln)),
     rc=_vcheck.returncode, line=_ln,
     stderr=(_vcheck.stderr or "")[-700:] if _vcheck.returncode else None)
if _vcheck.returncode != 0:
    raise RuntimeError("vllm entry point still fails in a fresh interpreter: "
                       + (_vcheck.stderr or "")[-700:])

# Step 3: only now is it safe to import in this process.
_STATE = json.loads(INSTALL_MARKER.read_text(encoding="utf-8"))
import vllm
from vllm import LLM, SamplingParams
from vllm.inputs import TokensPrompt
from vllm.lora.request import LoRARequest
import torch as _torch_after
diag("vllm_imports", ok=True, vllm=vllm.__version__,
     torch=_torch_after.__version__, cuda=_torch_after.version.cuda,
     protobuf=_protobuf_version(), gemma4_archs=_STATE.get("gemma4"),
     note="torch here must be the post-install 2.13.0, not the runner 2.10.0")
'''

OLD_TAIL_START = "# Step 2: a fresh interpreter reached this point, vLLM is verified. Import it."

if OLD_TAIL_START in src:
    i = src.index(OLD_TAIL_START)
    j = src.index("CODE_FETCH = ")
    src = src[:i] + REPAIR.lstrip("\n") + "'''\n\n" + src[j:]

    # The fetch cell no longer repairs protobuf; the install cell owns it.
    fs = src.index("CODE_FETCH = ")
    fe = src.index("CODE_PROMPTS = ")
    fetch = src[fs:fe]
    k = fetch.find("# v17 installed vLLM successfully")
    m = fetch.find('BASE = "google/gemma-4-31b-it-qat-w4a16-ct"')
    if k != -1 and m > k:
        fetch = fetch[:k] + fetch[m:]
        src = src[:fs] + fetch + src[fe:]
    io.open(P, "w", encoding="utf-8").write(src)

# ---- verify -------------------------------------------------------------
src = io.open(P, encoding="utf-8").read()
ast.parse(src)
mod = {}
exec(compile(ast.parse(src), "vllm_cells", "exec"), mod)
install = mod["CODE_INSTALL"]
fetch = mod["CODE_FETCH"]
# Only the install cell imports vllm's entry point; the fetch cell just
# downloads things. Assert that split rather than expecting both to.
for name, body in (("CODE_INSTALL", install), ("CODE_FETCH", fetch)):
    ast.parse(body)
    code = "\n".join(l.split("#", 1)[0] for l in body.splitlines())
    if name == "CODE_INSTALL":
        assert "from vllm import LLM" in code, "install cell lost the vllm import"
        assert "vllm_entrypoint_import" in code, "install lost the entry-point check"
    else:
        assert "from vllm import" not in code, \
            "fetch cell should not import vllm; the install cell owns that"
        assert "protobuf" not in code, \
            "fetch cell still repairs protobuf; that belongs to the install cell"
        assert "snapshot_download" in code, "fetch cell lost the checkpoint download"

# The ordering that v17 got wrong, asserted explicitly. Anchor on the
# IN-PROCESS import, not on any mention: the string "from vllm import LLM"
# also appears in an explanatory comment and in the subprocess -c probe, both of
# which sit BEFORE the repair by design.
i_pb = install.index("protobuf_upgrade")
i_imp = install.index("\nfrom vllm import LLM, SamplingParams")
assert 0 <= i_pb < i_imp, (
    f"protobuf repair at {i_pb} must precede the in-process vllm import at "
    f"{i_imp}; this is exactly how v17 failed")
assert "protobuf_upgrade" not in fetch, "fetch cell should not repair protobuf twice"
print("module parses; CODE_INSTALL and CODE_FETCH parse")
print("protobuf repair precedes the vllm entry-point import (v17 ordering fixed)")
